[package]
name = "rust-hackmdio"
version = "0.1.0"
authors = ["Jesse Wiles <jesse.wiles+rust-hackmdio@gmail.com>"]
edition = "2021"

[dependencies]
clap = "4.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }

